substitutions:
  name: "network-ups"
  friendly_name: "Network UPS"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
    

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: 5.5.1
    sdkconfig_options:
        CONFIG_USB_OTG_SUPPORTED: "y"
        CONFIG_USB_HOST_CONTROL_TRANSFER_MAX_SIZE: "256"
        CONFIG_ESP_CONSOLE_UART_DEFAULT: "y"
        CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG: "n"


packages:
  remote_package: github://wifijt/esp32-cyberpower-ups/cyberpower-ups.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
api:

ota:
  platform: esphome

logger:
  level: DEBUG
  
