substitutions:
  name: "cyberpower-ups"
  friendly_name: "CyberPower UPS"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

# FIXED: Platform moved to its own block
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# FIXED: Explicitly use Git source
external_components:
  - source:
      type: git
      url: https://github.com/wifijt/esp32-cyberpower-ups
    components: [ cyberpower_ups ]

# Initialize the UPS Driver
cyberpower_ups:
  id: ups_device

# Expose the sensors
sensor:
  - platform: cyberpower_ups
    watts:
      name: "${friendly_name} Output Watts"
    va:
      name: "${friendly_name} Output VA"
    load:
      name: "${friendly_name} Load"
    battery:
      name: "${friendly_name} Battery"

binary_sensor:
  - platform: cyberpower_ups
    online_status:
      name: "${friendly_name} Power Status"
    id: power_status
text_sensor:
  # This converts the binary 'online' status into friendly text
  - platform: template
    name: "${friendly_name} Status"
    id: ups_status_text
    icon: "mdi:power-settings"
    lambda: |-
      if (id(power_status).state) {
        return {"Mains (AC)"};
